#!/usr/bin/env node
/**
 *   node scripts/modules/generate.mjs           schreibt packages/toolkit/src/lib/all-modules.json
 *   node scripts/modules/generate.mjs --check   faellt, wenn die Datei nicht mehr zum Register passt
 */
import { readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"
import { reference, root } from "./lib.mjs"

export const target = resolve(root, "packages/toolkit/src/lib/all-modules.json")
export function render() {
  const { modules, errors } = reference()
  if (errors.length) { console.error(`module reference: ${errors.length} problem(s)\n${errors.map((e) => `  ${e}`).join("\n")}`); process.exit(1) }
  return `${JSON.stringify({ $comment: "Generated by scripts/modules/generate.mjs from the module register and the hint table. Do not edit; run pnpm docs:modules.", modules }, null, 2)}\n`
}
const out = render()
if (process.argv.includes("--check")) {
  let current = ""
  try { current = readFileSync(target, "utf8") } catch { /* fehlt */ }
  if (current !== out) { console.error(`module reference: ${target.slice(root.length)} is stale — run pnpm docs:modules`); process.exit(1) }
  console.log(`module reference: ${JSON.parse(out).modules.length} modules, file up to date`)
} else {
  writeFileSync(target, out)
  console.log(`module reference: ${JSON.parse(out).modules.length} modules → ${target.slice(root.length)}`)
}
