#!/usr/bin/env node
/**
 * Erzeugt `packages/toolkit/src/hooks/all-hooks.json` aus den TSDoc-Bloecken
 * der oeffentlichen Hooks (Plan D2). Die Storybook-Seite „All hooks" rendert
 * diese Datei; sie ist eingecheckt, damit Storybook ohne Skriptlauf baut.
 *
 *   node scripts/hooks/generate.mjs           schreibt die Datei
 *   node scripts/hooks/generate.mjs --check   faellt, wenn sie nicht mehr zum Code passt
 */
import { readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"
import { GROUPS, checkReference, reference, root } from "./lib.mjs"

export const target = resolve(root, "packages/toolkit/src/hooks/all-hooks.json")

/** Die Referenz als JSON-Text — ohne Zeitstempel, damit „frisch" pruefbar bleibt. */
export function render(rows = reference()) {
  const groups = Object.entries(GROUPS).map(([id, title]) => ({
    id,
    title,
    hooks: rows.filter((r) => r.group === id).map((r) => ({
      name: r.name, signature: r.signature, question: r.question, answers: r.answers, without: r.without,
      stories: r.see_story ?? [], specs: r.see_spec ?? [], source: r.source, line: r.line,
    })),
  }))
  return `${JSON.stringify({ $comment: "Generated by scripts/hooks/generate.mjs from the hooks' documentation comments. Do not edit; run pnpm docs:hooks.", groups }, null, 2)}\n`
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split("/").pop())) {
  const rows = reference()
  const errors = checkReference(rows)
  if (errors.length) {
    console.error(`hooks reference: ${errors.length} problem(s)\n${errors.map((e) => `  ${e}`).join("\n")}`)
    process.exit(1)
  }
  const out = render(rows)
  if (process.argv.includes("--check")) {
    let current = ""
    try { current = readFileSync(target, "utf8") } catch { /* fehlt */ }
    if (current !== out) {
      console.error(`hooks reference: ${target.slice(root.length)} is stale — run pnpm docs:hooks`)
      process.exit(1)
    }
    console.log(`hooks reference: ${rows.length} hooks documented, page up to date`)
  } else {
    writeFileSync(target, out)
    console.log(`hooks reference: ${rows.length} hooks → ${target.slice(root.length)}`)
  }
}
